# Generated by Django 2.2.6 on 2019-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(None, 'Select ad status'), ('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
